backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images"
public_folder: "/assets/images"

collections:
  - name: "home"
    label: "Homepage"
    files:
      - file: "src/pages/index.md"
        label: "Homepage"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Intro Text", name: "body", widget: "markdown" }
