backend:
  name: git-gateway
  branch: main

local_backend: true

logo_url: src/assets/images/12877358034423930450.png

media_folder: "src/assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "layout", label: "Layout", widget: "hidden", default: "page" }
      - { name: "body", label: "Content", widget: "markdown" }

  - name: "intake"
    label: "Intake Info"
    files:
      - file: "src/pages/intake.md"
        label: "Intake Page"
        name: "intake"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "layout", label: "Layout", widget: "hidden", default: "page" }
          - { name: "body", label: "Content", widget: "markdown" }

  - name: "business"
    label: "Business Info"
    files:
      - file: "src/_data/site.json"
        label: "Site Settings"
        name: "site"
        fields:
          - { name: "name", label: "Business Name", widget: "string" }
          - { name: "tagline", label: "Tagline", widget: "string", required: false }
          - { name: "phone", label: "Phone", widget: "string" }
          - { name: "email", label: "Email", widget: "string" }
          - { name: "address", label: "Address", widget: "text", required: false }
          - { name: "hours", label: "Hours", widget: "text", required: false }
          - { name: "cta", label: "Primary CTA Text", widget: "string", required: false }


