backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Homepage"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Intro Text", name: "body", widget: "markdown", hint: "Main welcome text" }

  - name: "services"
    label: "Service Tiers"
    folder: "src/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Service Name", name: "title", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Price", name: "price", widget: "number", value_type: "float", hint: "In USD" }
      - { label: "Active", name: "active", widget: "boolean", default: true }

  - name: "referrals"
    label: "Referral Logic"
    file: "src/_data/referrals.json"
    fields:
      - { label: "Referral Bonus Amount", name: "bonus", widget: "number" }
      - { label: "Max Payouts Per Customer", name: "max_payouts", widget: "number" }
